//! Chord charts: a progression written in numerals, and the catalogue of named ones.

use std::fmt;

use crate::time::Ticks;

use super::chord::Chord;
use super::key::Key;
use super::numeral::Numeral;

/// A progression, one bar per entry.
///
/// Chords inside a bar split it evenly, which is how a chart is read: `| Am | F G |` is two bars,
/// the second holding two chords of half a bar each.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Chart {
    /// The numerals, grouped by bar.
    pub bars: Vec<Vec<Numeral>>,
    /// Where the chart came from, which decides whether it may be rewritten.
    pub origin: ChartOrigin,
}

/// Where a chart came from.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum ChartOrigin {
    /// Typed by the user, or quoted from the catalogue. Never rewritten.
    ///
    /// This is what keeps a quoted progression sounding like the song it came from: colouring
    /// and cadence scheduling would turn 丸サ's floating loop into something that lands.
    Given,
    /// Generated by the composer, and therefore fair game for cadences and colour.
    Generated,
}

impl Chart {
    /// A chart from bars of numerals.
    pub fn new(bars: Vec<Vec<Numeral>>, origin: ChartOrigin) -> Self {
        Self { bars, origin }
    }

    /// How many bars the chart occupies.
    pub fn bar_count(&self) -> usize {
        self.bars.len()
    }

    /// `true` when the chart has no chords at all.
    pub fn is_empty(&self) -> bool {
        self.bars.iter().all(|bar| bar.is_empty())
    }

    /// Reads a chart: `| IVmaj7 | III7 | vi | I7 |`, or `@marusa` to name one.
    ///
    /// The outer pipes are optional and a bar may hold several chords. `@name x2` repeats a
    /// catalogue entry, which is how an eight-bar verse is written over a four-bar loop.
    pub fn parse(text: &str) -> Option<Self> {
        let text = text.trim();
        if let Some(rest) = text.strip_prefix('@') {
            // Split on whitespace, not on `x`: a name may contain one, and `@axis x2` must not
            // be read as the name `a` repeated `is x2` times.
            let (name, repeats) = match rest.split_once(char::is_whitespace) {
                Some((name, count)) => {
                    let repeats: usize = count.trim().trim_start_matches('x').parse().ok()?;
                    // A repeat count large enough to exhaust memory is a typo, not a request.
                    if !(1..=64).contains(&repeats) {
                        return None;
                    }
                    (name.trim(), repeats)
                }
                None => (rest.trim(), 1),
            };
            let chart = catalog(name)?;
            let bars = chart
                .bars
                .iter()
                .cycle()
                .take(chart.bars.len() * repeats.max(1))
                .cloned()
                .collect();
            return Some(Self::new(bars, ChartOrigin::Given));
        }

        let mut bars = Vec::new();
        for bar in text.split('|') {
            let bar = bar.trim();
            if bar.is_empty() {
                continue;
            }
            let mut chords = Vec::new();
            for symbol in bar.split_whitespace() {
                chords.push(Numeral::parse(symbol)?);
            }
            bars.push(chords);
        }
        (!bars.is_empty()).then(|| Self::new(bars, ChartOrigin::Given))
    }

    /// The chart repeated or truncated to exactly `bars` bars.
    ///
    /// Repeating rather than stretching: a four-bar loop under an eight-bar verse is played
    /// twice, which is what every band does and what every listener expects.
    pub fn fit_to(&self, bars: usize) -> Self {
        if self.bars.is_empty() || bars == 0 {
            return Self::new(Vec::new(), self.origin);
        }
        let fitted = self.bars.iter().cycle().take(bars).cloned().collect();
        Self::new(fitted, self.origin)
    }

    /// Where each chord falls, laid out from tick zero, before it is read against any key.
    ///
    /// `bar_ticks` is the length of one bar. Chords inside a bar divide it evenly, with any
    /// remainder given to the last chord so the bar always adds up exactly — a three-chord bar in
    /// 4/4 is 1280 + 1280 + 1280, and never 1280 + 1280 + 1279.
    ///
    /// Both [`Self::resolve`] and [`Harmony::stamp`](crate::harmony::Harmony::stamp) go through
    /// here, so a chart and the timeline stamped from it divide a bar the same way by
    /// construction rather than because two people wrote the same arithmetic twice.
    pub fn positions(&self, bar_ticks: Ticks) -> Vec<ChartSlot> {
        let mut slots = Vec::new();
        for (index, bar) in self.bars.iter().enumerate() {
            if bar.is_empty() {
                continue;
            }
            let bar_start = bar_ticks * index as i64;
            let share = Ticks(bar_ticks.raw() / bar.len() as i64);
            for (position, numeral) in bar.iter().enumerate() {
                let start = bar_start + share * position as i64;
                let end = if position + 1 == bar.len() {
                    bar_start + bar_ticks
                } else {
                    bar_start + share * (position + 1) as i64
                };
                slots.push(ChartSlot {
                    numeral: *numeral,
                    start,
                    length: end - start,
                    bar: index,
                });
            }
        }
        slots
    }

    /// The chords this chart means in `key`, laid out from tick zero.
    ///
    /// `bar_ticks` is the length of one bar; see [`Self::positions`] for how a bar is divided.
    pub fn resolve(&self, key: Key, bar_ticks: Ticks) -> Vec<HarmonicEvent> {
        self.positions(bar_ticks)
            .into_iter()
            .map(|slot| HarmonicEvent {
                numeral: slot.numeral,
                chord: slot.numeral.chord_in(key),
                key,
                start: slot.start,
                length: slot.length,
                bar: slot.bar,
            })
            .collect()
    }
}

/// Where one chord of a chart falls, before any key has been chosen.
///
/// This is [`HarmonicEvent`] minus the two things a key decides. Laying a chart onto a timeline
/// does not need them: the timeline stores numerals and reads them against whatever key is in
/// force where they land, which may not be one key for the whole chart.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub struct ChartSlot {
    /// The numeral written there.
    pub numeral: Numeral,
    /// Where it starts, from the beginning of the chart.
    pub start: Ticks,
    /// How long it sounds.
    pub length: Ticks,
    /// Which bar of the chart it falls in, counting from zero.
    pub bar: usize,
}

impl fmt::Display for Chart {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        for bar in &self.bars {
            f.write_str("| ")?;
            for numeral in bar {
                write!(f, "{numeral} ")?;
            }
        }
        f.write_str("|")
    }
}

/// One chord in time: what it is, where it is, and how long it lasts.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub struct HarmonicEvent {
    /// The numeral it was written as.
    pub numeral: Numeral,
    /// The chord that numeral means in this key.
    pub chord: Chord,
    /// The key it was resolved against, which a section may have transposed.
    pub key: Key,
    /// Where it starts, from the beginning of the section.
    pub start: Ticks,
    /// How long it sounds.
    pub length: Ticks,
    /// Which bar of the section it falls in.
    pub bar: usize,
}

impl HarmonicEvent {
    /// Position just past the end of the chord.
    pub fn end(&self) -> Ticks {
        self.start + self.length
    }

    /// `true` when `tick` falls inside the chord.
    pub fn contains(&self, tick: Ticks) -> bool {
        tick >= self.start && tick < self.end()
    }
}

/// A named progression from the catalogue.
pub struct CatalogEntry {
    /// The name the text format writes, after an `@`.
    pub name: &'static str,
    /// What it is, for a listing.
    pub description: &'static str,
    /// The chart, in the notation [`Chart::parse`] reads.
    pub chart: &'static str,
}

/// Every progression the composer knows by name.
///
/// Quoted rather than derived: these are specific, named, culturally located progressions, and
/// the whole value of naming one is that it comes out sounding like itself.
pub const CATALOG: &[CatalogEntry] = &[
    CatalogEntry {
        name: "axis",
        description: "The four chords of a thousand pop songs",
        chart: "| I | V | vi | IV |",
    },
    CatalogEntry {
        name: "axis-minor",
        description: "The same four chords starting from the relative minor",
        chart: "| vi | IV | I | V |",
    },
    CatalogEntry {
        name: "epic",
        description: "The minor axis: dark, modal, and everywhere in game music",
        chart: "| i | bVI | bIII | bVII |",
    },
    CatalogEntry {
        name: "komuro",
        description: "小室進行: minor start resolving to major",
        chart: "| vi | IV | V | I |",
    },
    CatalogEntry {
        name: "marusa",
        description: "丸サ進行: the Just-the-Two-of-Us loop that never lands on a tonic",
        chart: "| IVmaj7 | III7 | vi7 | I7 |",
    },
    CatalogEntry {
        name: "marusa5",
        description: "丸サ進行 with the ii-V into the subdominant spelled out",
        chart: "| IVmaj7 | III7 | vi7 | v7 I7 |",
    },
    CatalogEntry {
        name: "royal-road",
        description: "王道進行 (4536): the J-pop staple",
        chart: "| IVmaj7 | V7 | iii7 | vi |",
    },
    CatalogEntry {
        name: "koakuma",
        description: "小悪魔進行: 王道進行 with the dominant over a subdominant pedal",
        chart: "| IVmaj7 | V/4 | iii7 | vi |",
    },
    CatalogEntry {
        name: "naki",
        description: "泣きの進行: the royal road with a secondary dominant in its third bar",
        chart: "| IV | V | III7 | vi |",
    },
    CatalogEntry {
        name: "canon",
        description: "カノン進行, after Pachelbel",
        chart: "| I | V | vi | iii | IV | I | IV | V |",
    },
    CatalogEntry {
        name: "junjo",
        description: "純情進行: the canon over a stepwise descending bass",
        chart: "| I | V/7 | vi | iii/5 | IV | I/3 | ii | V |",
    },
    CatalogEntry {
        name: "doo-wop",
        description: "The fifties progression",
        chart: "| I | vi | IV | V |",
    },
    CatalogEntry {
        name: "ii-v-i",
        description: "The cadence jazz is built on",
        chart: "| ii7 | V7 | Imaj7 | Imaj7 |",
    },
    CatalogEntry {
        name: "blues",
        description: "Twelve-bar blues with a quick change and a turnaround",
        chart: "| I7 | IV7 | I7 | I7 | IV7 | IV7 | I7 | I7 | V7 | IV7 | I7 | V7 |",
    },
    CatalogEntry {
        name: "andalusian",
        description: "The descending tetrachord: i bVII bVI V",
        chart: "| i | bVII | bVI | V |",
    },
    CatalogEntry {
        name: "sad-loop",
        description: "A four-bar loop that keeps turning back on itself",
        chart: "| vi | IV | I | V |",
    },
];

/// The catalogue entry with this name, accepting the Japanese names too.
pub fn catalog(name: &str) -> Option<Chart> {
    let normalised = match name.trim() {
        "丸サ" | "丸サ進行" => "marusa",
        "王道" | "王道進行" => "royal-road",
        "小悪魔" | "小悪魔進行" => "koakuma",
        "小室" | "小室進行" => "komuro",
        "カノン" | "カノン進行" | "pachelbel" => "canon",
        "純情" | "純情進行" => "junjo",
        "泣き" | "泣きの進行" => "naki",
        "50s" | "fifties" => "doo-wop",
        "blues12" | "twelve-bar" => "blues",
        other => other,
    };
    CATALOG
        .iter()
        .find(|entry| entry.name == normalised)
        .and_then(|entry| Chart::parse(entry.chart))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::time::TICKS_PER_QUARTER;

    /// One bar of four four, in ticks.
    const BAR: Ticks = Ticks(TICKS_PER_QUARTER * 4);

    fn key(text: &str) -> Key {
        Key::parse(text).unwrap()
    }

    fn chord_names(chart: &Chart, key_text: &str) -> Vec<String> {
        chart
            .resolve(key(key_text), BAR)
            .iter()
            .map(|event| event.chord.to_string())
            .collect()
    }

    #[test]
    fn a_chart_reads_bar_by_bar() {
        let chart = Chart::parse("| I | V | vi | IV |").unwrap();
        assert_eq!(chart.bar_count(), 4);
        assert_eq!(chord_names(&chart, "C major"), ["C", "G", "Am", "F"]);
    }

    #[test]
    fn outer_pipes_are_optional_and_whitespace_is_free() {
        let a = Chart::parse("| I | V |").unwrap();
        let b = Chart::parse("I | V").unwrap();
        let c = Chart::parse("  I  |  V  ").unwrap();
        assert_eq!(a.bars, b.bars);
        assert_eq!(b.bars, c.bars);
    }

    #[test]
    fn two_chords_in_a_bar_split_it_evenly() {
        let chart = Chart::parse("| I | ii V |").unwrap();
        let events = chart.resolve(key("C major"), BAR);
        assert_eq!(events.len(), 3);
        assert_eq!(events[0].start, Ticks::ZERO);
        assert_eq!(events[0].length, BAR);
        assert_eq!(events[1].start, BAR);
        assert_eq!(events[1].length, Ticks(BAR.raw() / 2));
        assert_eq!(events[2].start, BAR + Ticks(BAR.raw() / 2));
        assert_eq!(events[2].length, Ticks(BAR.raw() / 2));
        assert_eq!(events[2].end(), BAR * 2, "the bar adds up exactly");
    }

    #[test]
    fn three_chords_in_a_bar_still_add_up_exactly() {
        // 4/4 does not divide by three; the remainder goes to the last chord rather than
        // leaving a gap the scheduler would render as silence.
        let chart = Chart::parse("| I ii V |").unwrap();
        let events = chart.resolve(key("C major"), BAR);
        assert_eq!(events.len(), 3);
        assert_eq!(events.last().unwrap().end(), BAR);
        let total: i64 = events.iter().map(|event| event.length.raw()).sum();
        assert_eq!(total, BAR.raw());
    }

    #[test]
    fn fitting_repeats_a_loop_and_truncates_a_long_one() {
        let chart = Chart::parse("| I | V |").unwrap();
        assert_eq!(chart.fit_to(4).bar_count(), 4);
        assert_eq!(
            chord_names(&chart.fit_to(4), "C major"),
            ["C", "G", "C", "G"]
        );
        assert_eq!(chart.fit_to(1).bar_count(), 1);
        assert_eq!(chart.fit_to(0).bar_count(), 0);
    }

    #[test]
    fn every_catalogue_entry_parses_and_is_named_once() {
        let mut seen = Vec::new();
        for entry in CATALOG {
            let chart = Chart::parse(entry.chart)
                .unwrap_or_else(|| panic!("`{}` does not parse: {}", entry.name, entry.chart));
            assert!(!chart.is_empty(), "`{}` is empty", entry.name);
            assert!(
                !seen.contains(&entry.name),
                "`{}` is listed twice",
                entry.name
            );
            assert!(!entry.description.is_empty());
            seen.push(entry.name);
            // And it resolves in both a major and a minor key without panicking.
            assert!(!chart.resolve(key("C major"), BAR).is_empty());
            assert!(!chart.resolve(key("A minor"), BAR).is_empty());
        }
    }

    #[test]
    fn the_named_progressions_come_out_as_the_chords_they_are_famous_for() {
        assert_eq!(
            chord_names(&catalog("marusa").unwrap(), "C major"),
            ["Fmaj7", "E7", "Am7", "C7"],
            "丸サ進行 in C"
        );
        assert_eq!(
            chord_names(&catalog("royal-road").unwrap(), "C major"),
            ["Fmaj7", "G7", "Em7", "Am"],
            "王道進行 in C"
        );
        assert_eq!(
            chord_names(&catalog("axis").unwrap(), "C major"),
            ["C", "G", "Am", "F"]
        );
        assert_eq!(
            chord_names(&catalog("epic").unwrap(), "A minor"),
            ["Am", "F", "C", "G"]
        );
        assert_eq!(
            chord_names(&catalog("andalusian").unwrap(), "A minor"),
            ["Am", "G", "F", "E"],
            "the descending tetrachord, with a major dominant at the end"
        );
    }

    #[test]
    fn the_koakuma_pedal_puts_the_subdominant_under_the_dominant() {
        let events = catalog("koakuma").unwrap().resolve(key("C major"), BAR);
        // F - G/F - Em - Am: the bass stays on F for two bars, which is the whole point.
        assert_eq!(events[1].chord.to_string(), "G/F");
        assert_eq!(events[1].chord.bass_class().sharp_name(), "F");
    }

    #[test]
    fn the_junjo_bass_descends_stepwise() {
        let events = catalog("junjo").unwrap().resolve(key("C major"), BAR);
        let bass: Vec<&str> = events
            .iter()
            .map(|event| event.chord.bass_class().sharp_name())
            .collect();
        assert_eq!(bass, ["C", "B", "A", "G", "F", "E", "D", "G"]);
    }

    #[test]
    fn a_catalogue_entry_can_be_named_and_repeated() {
        let once = Chart::parse("@axis").unwrap();
        let twice = Chart::parse("@axis x2").unwrap();
        assert_eq!(once.bar_count(), 4);
        assert_eq!(twice.bar_count(), 8);
        assert_eq!(twice.bars[4], once.bars[0]);
        assert!(Chart::parse("@nonsense").is_none());
    }

    #[test]
    fn the_japanese_names_reach_the_same_charts() {
        assert_eq!(catalog("丸サ進行"), catalog("marusa"));
        assert_eq!(catalog("王道進行"), catalog("royal-road"));
        assert_eq!(catalog("小悪魔"), catalog("koakuma"));
    }

    #[test]
    fn a_chart_round_trips_through_its_text() {
        let chart = Chart::parse("| IVmaj7 | III7 | vi7 | I7 |").unwrap();
        assert_eq!(chart.to_string(), "| IVmaj7 | III7 | vi7 | I7 |");
        assert_eq!(Chart::parse(&chart.to_string()).unwrap().bars, chart.bars);
    }

    #[test]
    fn nonsense_is_rejected_rather_than_silently_dropped() {
        assert!(Chart::parse("| I | nonsense |").is_none());
        assert!(Chart::parse("").is_none());
        assert!(Chart::parse("| |").is_none());
    }
}
