//! Chord charts: a progression written in numerals, and the catalogue of named ones.

use std::fmt;

use crate::time::Ticks;

use super::chord::Chord;
use super::key::Key;
use super::numeral::Numeral;

/// A progression, one bar per entry.
///
/// Chords inside a bar split it evenly, which is how a chart is read: `| Am | F G |` is two bars,
/// the second holding two chords of half a bar each.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Chart {
    /// The numerals, grouped by bar.
    pub bars: Vec<Vec<Numeral>>,
    /// Where the chart came from, which decides whether it may be rewritten.
    pub origin: ChartOrigin,
    /// The mode the numerals are written in, when the chart knows.
    ///
    /// `None` for a chart somebody wrote out by hand: those are the degrees they meant, and
    /// nothing should second-guess them. A catalogue entry does know, and [`Self::spelled_in`]
    /// is what it knows it for.
    pub mode: Option<ChartMode>,
    /// The catalogue name this was quoted from, without the `@`, and with any repeat count.
    ///
    /// So that a document that said `@marusa` can be written back saying `@marusa` rather than
    /// four bars of numerals — which is both shorter to read and the only way the *mode* comes
    /// back with it, since a spelled-out chart cannot say which mode it was written in.
    pub quoted_as: Option<String>,
}

/// Where a chart came from.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum ChartOrigin {
    /// Typed by the user, or quoted from the catalogue. Never rewritten.
    ///
    /// This is what keeps a quoted progression sounding like the song it came from: colouring
    /// and cadence scheduling would turn 丸サ's floating loop into something that lands.
    Given,
    /// Generated by the composer, and therefore fair game for cadences and colour.
    Generated,
}

/// The mode a progression's degrees are written against.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum ChartMode {
    /// `I` is the tonic and `vi` its relative minor: the ordinary major-key chart.
    Major,
    /// `i` is the tonic: `| i | bVI | bIII | bVII |` and its kind.
    Minor,
}

impl ChartMode {
    /// Which mode a key is in.
    pub fn of(key: Key) -> Self {
        if key.is_minor() {
            Self::Minor
        } else {
            Self::Major
        }
    }

    /// `true` when a chart in this mode can be read against `key` as written.
    pub fn suits(self, key: Key) -> bool {
        Self::of(key) == self
    }
}

impl Chart {
    /// A chart from bars of numerals, in no declared mode.
    pub fn new(bars: Vec<Vec<Numeral>>, origin: ChartOrigin) -> Self {
        Self {
            bars,
            origin,
            mode: None,
            quoted_as: None,
        }
    }

    /// The same chart, saying which mode its degrees are written against.
    pub fn written_in(self, mode: ChartMode) -> Self {
        Self {
            mode: Some(mode),
            ..self
        }
    }

    /// A progression nobody has written yet: the request that the composer invent one.
    ///
    /// A marker, not a chart — it has no bars, and anything that resolved it directly would get
    /// silence. Whoever plans a piece is expected to ask [`Self::is_unwritten`] and put a real
    /// progression in its place; keeping the marker in the ordinary `Chart` type is what lets a
    /// song file, a picker and a specification all point a section at "whatever the composer
    /// comes up with" without a second kind of chart existing everywhere charts travel.
    pub fn unwritten() -> Self {
        Self::new(Vec::new(), ChartOrigin::Generated)
    }

    /// `true` for the [`Self::unwritten`] marker: a progression left to the composer to invent.
    ///
    /// An empty *given* chart is not one — that is a chart somebody cleared, and it means
    /// silence, not "surprise me".
    pub fn is_unwritten(&self) -> bool {
        self.bars.is_empty() && self.origin == ChartOrigin::Generated
    }

    /// The same progression, its numerals read against `key`.
    ///
    /// A named progression is written in a mode, and asking for it in the other one used to read
    /// its degrees literally — so 丸サ進行 in C minor came out Fmaj7 – Eb7 – Abm7 – C7, which
    /// shares one chord with the loop anybody means by the name and lands nowhere near it. The
    /// chords are what a quoted progression *is*, so the numerals are resolved against the
    /// relative key they were written for and renamed for the key the piece is in: the same four
    /// chords, centred where the piece is centred.
    ///
    /// A chart nobody named — one written out by hand — declares no mode and is returned
    /// unchanged. Those are the degrees the person meant.
    pub fn spelled_in(&self, key: Key) -> Self {
        let Some(mode) = self.mode else {
            return self.clone();
        };
        if mode.suits(key) {
            return self.clone();
        }
        let written_for = key.relative();
        Self {
            bars: self
                .bars
                .iter()
                .map(|bar| {
                    bar.iter()
                        .map(|numeral| numeral.respelled_in(written_for, key))
                        .collect()
                })
                .collect(),
            origin: self.origin,
            mode: Some(ChartMode::of(key)),
            // Still the same quotation: the name is what these numerals were derived from, and
            // reading it again in the same key gives them back.
            quoted_as: self.quoted_as.clone(),
        }
    }

    /// How many bars the chart occupies.
    pub fn bar_count(&self) -> usize {
        self.bars.len()
    }

    /// `true` when the chart has no chords at all.
    pub fn is_empty(&self) -> bool {
        self.bars.iter().all(|bar| bar.is_empty())
    }

    /// Reads a chart: `| IVmaj7 | III7 | vi | I7 |`, or `@marusa` to name one.
    ///
    /// The outer pipes are optional and a bar may hold several chords. `@name x2` repeats a
    /// catalogue entry, which is how an eight-bar verse is written over a four-bar loop.
    pub fn parse(text: &str) -> Option<Self> {
        let text = text.trim();
        if let Some(rest) = text.strip_prefix('@') {
            // Split on whitespace, not on `x`: a name may contain one, and `@axis x2` must not
            // be read as the name `a` repeated `is x2` times.
            let (name, repeats) = match rest.split_once(char::is_whitespace) {
                Some((name, count)) => {
                    let repeats: usize = count.trim().trim_start_matches('x').parse().ok()?;
                    // A repeat count large enough to exhaust memory is a typo, not a request.
                    if !(1..=64).contains(&repeats) {
                        return None;
                    }
                    (name.trim(), repeats)
                }
                None => (rest.trim(), 1),
            };
            let chart = catalog(name)?;
            let quoted = chart.quoted_as.clone().unwrap_or_else(|| name.to_string());
            let quoted = if repeats > 1 {
                format!("{quoted} x{repeats}")
            } else {
                quoted
            };
            return Some(Chart {
                quoted_as: Some(quoted),
                ..chart.fit_to(chart.bars.len() * repeats.max(1))
            });
        }

        // The outer pipes are optional, which is what makes the first and last piece empty when
        // they are written. Only those two: a `|` in the middle with nothing on either side of it
        // was being skipped by the same rule, so `| I | | V | IV |` — a doubled pipe, which is
        // what a paste or a stray keystroke leaves behind — read as three bars and moved every
        // chord after the gap a bar earlier than the section it belongs under, without saying so.
        // There is no way to write an empty bar on purpose here, so the answer is not to guess at
        // one: a chart that cannot be read is refused, as a chart of nothing already was.
        let mut pieces: Vec<&str> = text.split('|').collect();
        if pieces.first().is_some_and(|piece| piece.trim().is_empty()) {
            pieces.remove(0);
        }
        if pieces.last().is_some_and(|piece| piece.trim().is_empty()) {
            pieces.pop();
        }

        let mut bars = Vec::new();
        for bar in pieces {
            let bar = bar.trim();
            if bar.is_empty() {
                return None;
            }
            let mut chords = Vec::new();
            for symbol in bar.split_whitespace() {
                chords.push(Numeral::parse(symbol)?);
            }
            bars.push(chords);
        }
        (!bars.is_empty()).then(|| Self::new(bars, ChartOrigin::Given))
    }

    /// The chart repeated or truncated to exactly `bars` bars.
    ///
    /// Repeating rather than stretching: a four-bar loop under an eight-bar verse is played
    /// twice, which is what every band does and what every listener expects.
    pub fn fit_to(&self, bars: usize) -> Self {
        let length = self.bars.len();
        let fitted = if length == 0 || bars == 0 {
            Vec::new()
        } else if bars <= length {
            // Shorter than the chart, so this is a fragment of it, and a fragment starts at the
            // beginning: a section opening on the tonic sits where a section should, and there is
            // no cadence to preserve in two bars anyway.
            self.bars[..bars].to_vec()
        } else {
            // Longer. As many whole passes as fit, and the odd bars taken from the *end* of the
            // chart rather than its start — so the section finishes on the chord the progression
            // finishes on, whatever its length. Cycling straight through instead left the last
            // bar wherever the arithmetic put it: six bars of a four-bar chart ended on its
            // second chord, mid-phrase, with the fill and any lead-in landing on a chord that was
            // still going somewhere. Repeating the approach to the cadence is what an arranger
            // does with the spare bars, and it keeps one chord to the bar while doing it.
            let remainder = bars % length;
            let mut fitted: Vec<_> = self
                .bars
                .iter()
                .cycle()
                .take(bars - remainder)
                .cloned()
                .collect();
            fitted.extend_from_slice(&self.bars[length - remainder..]);
            fitted
        };
        Self {
            bars: fitted,
            // A chart cut or repeated to a different length is no longer the quoted one, and
            // writing its name back out would give the wrong number of bars.
            quoted_as: None,
            ..self.clone()
        }
    }

    /// Where each chord falls, laid out from tick zero, before it is read against any key.
    ///
    /// `bar_ticks` is the length of one bar. Chords inside a bar divide it evenly, with any
    /// remainder given to the last chord so the bar always adds up exactly — a three-chord bar in
    /// 4/4 is 1280 + 1280 + 1280, and never 1280 + 1280 + 1279.
    ///
    /// Both [`Self::resolve`] and [`Harmony::stamp`](crate::harmony::Harmony::stamp) go through
    /// here, so a chart and the timeline stamped from it divide a bar the same way by
    /// construction rather than because two people wrote the same arithmetic twice.
    pub fn positions(&self, bar_ticks: Ticks) -> Vec<ChartSlot> {
        let mut slots = Vec::new();
        for (index, bar) in self.bars.iter().enumerate() {
            if bar.is_empty() {
                continue;
            }
            let bar_start = bar_ticks * index as i64;
            let share = Ticks(bar_ticks.raw() / bar.len() as i64);
            for (position, numeral) in bar.iter().enumerate() {
                let start = bar_start + share * position as i64;
                let end = if position + 1 == bar.len() {
                    bar_start + bar_ticks
                } else {
                    bar_start + share * (position + 1) as i64
                };
                slots.push(ChartSlot {
                    numeral: *numeral,
                    start,
                    length: end - start,
                    bar: index,
                });
            }
        }
        slots
    }

    /// The chords this chart means in `key`, laid out from tick zero.
    ///
    /// `bar_ticks` is the length of one bar; see [`Self::positions`] for how a bar is divided.
    pub fn resolve(&self, key: Key, bar_ticks: Ticks) -> Vec<HarmonicEvent> {
        self.positions(bar_ticks)
            .into_iter()
            .map(|slot| HarmonicEvent {
                numeral: slot.numeral,
                chord: slot.numeral.chord_in(key),
                key,
                start: slot.start,
                length: slot.length,
                bar: slot.bar,
            })
            .collect()
    }
}

/// Where one chord of a chart falls, before any key has been chosen.
///
/// This is [`HarmonicEvent`] minus the two things a key decides. Laying a chart onto a timeline
/// does not need them: the timeline stores numerals and reads them against whatever key is in
/// force where they land, which may not be one key for the whole chart.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub struct ChartSlot {
    /// The numeral written there.
    pub numeral: Numeral,
    /// Where it starts, from the beginning of the chart.
    pub start: Ticks,
    /// How long it sounds.
    pub length: Ticks,
    /// Which bar of the chart it falls in, counting from zero.
    pub bar: usize,
}

impl fmt::Display for Chart {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        for bar in &self.bars {
            f.write_str("| ")?;
            for numeral in bar {
                write!(f, "{numeral} ")?;
            }
        }
        f.write_str("|")
    }
}

/// One chord in time: what it is, where it is, and how long it lasts.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub struct HarmonicEvent {
    /// The numeral it was written as.
    pub numeral: Numeral,
    /// The chord that numeral means in this key.
    pub chord: Chord,
    /// The key it was resolved against, which a section may have transposed.
    pub key: Key,
    /// Where it starts, from the beginning of the section.
    pub start: Ticks,
    /// How long it sounds.
    pub length: Ticks,
    /// Which bar of the section it falls in.
    pub bar: usize,
}

impl HarmonicEvent {
    /// What the chord is called, spelled for the key it was resolved against.
    ///
    /// This is the name to put on screen. An event carries both the numeral and the key, which is
    /// everything needed to get the spelling right — [`Chord`]'s own [`Display`](fmt::Display) is
    /// a guess made without a key, and would call the tonic of E flat major a D sharp.
    pub fn name(&self) -> String {
        self.numeral.name_in(self.key)
    }

    /// Position just past the end of the chord.
    pub fn end(&self) -> Ticks {
        self.start + self.length
    }

    /// `true` when `tick` falls inside the chord.
    pub fn contains(&self, tick: Ticks) -> bool {
        tick >= self.start && tick < self.end()
    }
}

/// A named progression from the catalogue.
pub struct CatalogEntry {
    /// The name the text format writes, after an `@`.
    pub name: &'static str,
    /// What it is, for a listing.
    pub description: &'static str,
    /// The chart, in the notation [`Chart::parse`] reads.
    pub chart: &'static str,
    /// Which mode its degrees are written against, so it can be quoted into the other one.
    pub mode: ChartMode,
}

/// Every progression the composer knows by name.
///
/// Quoted rather than derived: these are specific, named, culturally located progressions, and
/// the whole value of naming one is that it comes out sounding like itself.
pub const CATALOG: &[CatalogEntry] = &[
    CatalogEntry {
        name: "axis",
        description: "The four chords of a thousand pop songs",
        chart: "| I | V | vi | IV |",
        mode: ChartMode::Major,
    },
    CatalogEntry {
        name: "axis-minor",
        description: "The same four chords starting from the relative minor",
        chart: "| vi | IV | I | V |",
        mode: ChartMode::Major,
    },
    CatalogEntry {
        name: "epic",
        description: "The minor axis: dark, modal, and everywhere in game music",
        chart: "| i | bVI | bIII | bVII |",
        mode: ChartMode::Minor,
    },
    CatalogEntry {
        name: "komuro",
        description: "小室進行: minor start resolving to major",
        chart: "| vi | IV | V | I |",
        mode: ChartMode::Major,
    },
    CatalogEntry {
        name: "marusa",
        description: "丸サ進行: the Just-the-Two-of-Us loop that never lands on a tonic",
        chart: "| IVmaj7 | III7 | vi7 | I7 |",
        mode: ChartMode::Major,
    },
    CatalogEntry {
        name: "marusa5",
        description: "丸サ進行 with the ii-V into the subdominant spelled out",
        chart: "| IVmaj7 | III7 | vi7 | v7 I7 |",
        mode: ChartMode::Major,
    },
    CatalogEntry {
        name: "royal-road",
        description: "王道進行 (4536): the J-pop staple",
        chart: "| IVmaj7 | V7 | iii7 | vi |",
        mode: ChartMode::Major,
    },
    CatalogEntry {
        name: "koakuma",
        description: "小悪魔進行: 王道進行 with the dominant over a subdominant pedal",
        chart: "| IVmaj7 | V/4 | iii7 | vi |",
        mode: ChartMode::Major,
    },
    CatalogEntry {
        name: "naki",
        description: "泣きの進行: the royal road with a secondary dominant in its third bar",
        chart: "| IV | V | III7 | vi |",
        mode: ChartMode::Major,
    },
    CatalogEntry {
        name: "canon",
        description: "カノン進行, after Pachelbel",
        chart: "| I | V | vi | iii | IV | I | IV | V |",
        mode: ChartMode::Major,
    },
    CatalogEntry {
        name: "junjo",
        description: "純情進行: the canon over a stepwise descending bass",
        chart: "| I | V/7 | vi | iii/5 | IV | I/3 | ii | V |",
        mode: ChartMode::Major,
    },
    CatalogEntry {
        name: "doo-wop",
        description: "The fifties progression",
        chart: "| I | vi | IV | V |",
        mode: ChartMode::Major,
    },
    CatalogEntry {
        name: "ii-v-i",
        description: "The cadence jazz is built on",
        chart: "| ii7 | V7 | Imaj7 | Imaj7 |",
        mode: ChartMode::Major,
    },
    CatalogEntry {
        name: "blues",
        description: "Twelve-bar blues with a quick change and a turnaround",
        chart: "| I7 | IV7 | I7 | I7 | IV7 | IV7 | I7 | I7 | V7 | IV7 | I7 | V7 |",
        mode: ChartMode::Major,
    },
    CatalogEntry {
        name: "andalusian",
        description: "The descending tetrachord: i bVII bVI V",
        chart: "| i | bVII | bVI | V |",
        mode: ChartMode::Minor,
    },
    CatalogEntry {
        name: "sad-loop",
        description: "A four-bar loop that keeps turning back on itself",
        chart: "| vi | IV | I | V |",
        mode: ChartMode::Major,
    },
];

/// The catalogue entry with this name, accepting the Japanese names too.
pub fn catalog(name: &str) -> Option<Chart> {
    let normalised = match name.trim() {
        "丸サ" | "丸サ進行" => "marusa",
        "王道" | "王道進行" => "royal-road",
        "小悪魔" | "小悪魔進行" => "koakuma",
        "小室" | "小室進行" => "komuro",
        "カノン" | "カノン進行" | "pachelbel" => "canon",
        "純情" | "純情進行" => "junjo",
        "泣き" | "泣きの進行" => "naki",
        "50s" | "fifties" => "doo-wop",
        "blues12" | "twelve-bar" => "blues",
        other => other,
    };
    CATALOG
        .iter()
        .find(|entry| entry.name == normalised)
        .and_then(|entry| {
            Chart::parse(entry.chart).map(|chart| Chart {
                // The canonical name, not the one that was asked for, so `@丸サ進行` and
                // `@marusa` are the same chart rather than two that merely sound alike.
                quoted_as: Some(entry.name.to_string()),
                ..chart.written_in(entry.mode)
            })
        })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::time::TICKS_PER_QUARTER;

    /// One bar of four four, in ticks.
    const BAR: Ticks = Ticks(TICKS_PER_QUARTER * 4);

    fn key(text: &str) -> Key {
        Key::parse(text).unwrap()
    }

    fn chord_names(chart: &Chart, key_text: &str) -> Vec<String> {
        chart
            .resolve(key(key_text), BAR)
            .iter()
            .map(|event| event.chord.to_string())
            .collect()
    }

    #[test]
    fn a_chart_reads_bar_by_bar() {
        let chart = Chart::parse("| I | V | vi | IV |").unwrap();
        assert_eq!(chart.bar_count(), 4);
        assert_eq!(chord_names(&chart, "C major"), ["C", "G", "Am", "F"]);
    }

    #[test]
    fn outer_pipes_are_optional_and_whitespace_is_free() {
        let a = Chart::parse("| I | V |").unwrap();
        let b = Chart::parse("I | V").unwrap();
        let c = Chart::parse("  I  |  V  ").unwrap();
        assert_eq!(a.bars, b.bars);
        assert_eq!(b.bars, c.bars);
    }

    #[test]
    fn two_chords_in_a_bar_split_it_evenly() {
        let chart = Chart::parse("| I | ii V |").unwrap();
        let events = chart.resolve(key("C major"), BAR);
        assert_eq!(events.len(), 3);
        assert_eq!(events[0].start, Ticks::ZERO);
        assert_eq!(events[0].length, BAR);
        assert_eq!(events[1].start, BAR);
        assert_eq!(events[1].length, Ticks(BAR.raw() / 2));
        assert_eq!(events[2].start, BAR + Ticks(BAR.raw() / 2));
        assert_eq!(events[2].length, Ticks(BAR.raw() / 2));
        assert_eq!(events[2].end(), BAR * 2, "the bar adds up exactly");
    }

    #[test]
    fn three_chords_in_a_bar_still_add_up_exactly() {
        // 4/4 does not divide by three; the remainder goes to the last chord rather than
        // leaving a gap the scheduler would render as silence.
        let chart = Chart::parse("| I ii V |").unwrap();
        let events = chart.resolve(key("C major"), BAR);
        assert_eq!(events.len(), 3);
        assert_eq!(events.last().unwrap().end(), BAR);
        let total: i64 = events.iter().map(|event| event.length.raw()).sum();
        assert_eq!(total, BAR.raw());
    }

    #[test]
    fn an_odd_length_section_still_ends_where_the_progression_ends() {
        // The spare bars come off the *end* of the chart, so the last bar of a section is the last
        // bar of the progression however many bars the section has. Cycling straight through left
        // it wherever the arithmetic put it — six bars of a four-bar chart ended on its second
        // chord, with the fill and any lead-in landing mid-phrase.
        let axis = catalog("axis").unwrap();
        assert_eq!(chord_names(&axis, "C major"), ["C", "G", "Am", "F"]);

        // One whole pass, then the approach to the cadence again.
        assert_eq!(
            chord_names(&axis.fit_to(6), "C major"),
            ["C", "G", "Am", "F", "Am", "F"]
        );
        assert_eq!(
            chord_names(&axis.fit_to(7), "C major"),
            ["C", "G", "Am", "F", "G", "Am", "F"]
        );
        assert_eq!(
            chord_names(&axis.fit_to(5), "C major"),
            ["C", "G", "Am", "F", "F"]
        );

        // An exact multiple is untouched, which is the ordinary case and every fixture.
        assert_eq!(
            chord_names(&axis.fit_to(8), "C major"),
            ["C", "G", "Am", "F", "C", "G", "Am", "F"]
        );

        // Shorter than the chart is a fragment, and a fragment starts at the beginning.
        assert_eq!(chord_names(&axis.fit_to(2), "C major"), ["C", "G"]);
        assert_eq!(chord_names(&axis.fit_to(1), "C major"), ["C"]);

        // Whatever the length, the section ends on the chord the progression ends on — except
        // where it was cut short deliberately.
        for bars in 4..=32 {
            let fitted = axis.fit_to(bars);
            assert_eq!(fitted.bar_count(), bars);
            assert_eq!(
                fitted.bars.last(),
                axis.bars.last(),
                "{bars} bars did not land on the chart's last chord"
            );
        }
    }

    #[test]
    fn fitting_repeats_a_loop_and_truncates_a_long_one() {
        let chart = Chart::parse("| I | V |").unwrap();
        assert_eq!(chart.fit_to(4).bar_count(), 4);
        assert_eq!(
            chord_names(&chart.fit_to(4), "C major"),
            ["C", "G", "C", "G"]
        );
        assert_eq!(chart.fit_to(1).bar_count(), 1);
        assert_eq!(chart.fit_to(0).bar_count(), 0);
    }

    #[test]
    fn every_catalogue_entry_parses_and_is_named_once() {
        let mut seen = Vec::new();
        for entry in CATALOG {
            let chart = Chart::parse(entry.chart)
                .unwrap_or_else(|| panic!("`{}` does not parse: {}", entry.name, entry.chart));
            assert!(!chart.is_empty(), "`{}` is empty", entry.name);
            assert!(
                !seen.contains(&entry.name),
                "`{}` is listed twice",
                entry.name
            );
            assert!(!entry.description.is_empty());
            seen.push(entry.name);
            // And it resolves in both a major and a minor key without panicking.
            assert!(!chart.resolve(key("C major"), BAR).is_empty());
            assert!(!chart.resolve(key("A minor"), BAR).is_empty());
        }
    }

    #[test]
    fn the_named_progressions_come_out_as_the_chords_they_are_famous_for() {
        assert_eq!(
            chord_names(&catalog("marusa").unwrap(), "C major"),
            ["Fmaj7", "E7", "Am7", "C7"],
            "丸サ進行 in C"
        );
        // Read literally against a minor key, degree by degree. Nobody asks for that — see
        // `a_named_progression_is_the_same_loop_in_the_other_mode` — but it is what the numerals
        // say, and `vi7` used to come out Abmaj7 here: a major third above a root written in
        // lower case.
        assert_eq!(
            chord_names(
                &catalog("marusa").unwrap().written_in(ChartMode::Minor),
                "C minor"
            ),
            ["Fmaj7", "Eb7", "Abm7", "C7"],
            "丸サ進行 in C minor, if its degrees were taken at face value"
        );
        assert_eq!(
            chord_names(&catalog("royal-road").unwrap(), "C major"),
            ["Fmaj7", "G7", "Em7", "Am"],
            "王道進行 in C"
        );
        assert_eq!(
            chord_names(&catalog("axis").unwrap(), "C major"),
            ["C", "G", "Am", "F"]
        );
        assert_eq!(
            chord_names(&catalog("epic").unwrap(), "A minor"),
            ["Am", "F", "C", "G"]
        );
        assert_eq!(
            chord_names(&catalog("andalusian").unwrap(), "A minor"),
            ["Am", "G", "F", "E"],
            "the descending tetrachord, with a major dominant at the end"
        );
    }

    #[test]
    fn the_koakuma_pedal_puts_the_subdominant_under_the_dominant() {
        let events = catalog("koakuma").unwrap().resolve(key("C major"), BAR);
        // F - G/F - Em - Am: the bass stays on F for two bars, which is the whole point.
        assert_eq!(events[1].chord.to_string(), "G/F");
        assert_eq!(events[1].chord.bass_class().sharp_name(), "F");
    }

    #[test]
    fn the_junjo_bass_descends_stepwise() {
        let events = catalog("junjo").unwrap().resolve(key("C major"), BAR);
        let bass: Vec<&str> = events
            .iter()
            .map(|event| event.chord.bass_class().sharp_name())
            .collect();
        assert_eq!(bass, ["C", "B", "A", "G", "F", "E", "D", "G"]);
    }

    #[test]
    fn an_unwritten_chart_is_a_marker_and_nothing_else_is() {
        let marker = Chart::unwritten();
        assert!(marker.is_unwritten());
        assert!(marker.is_empty());
        assert_eq!(marker.origin, ChartOrigin::Generated);

        // A chart with bars is a chart, whoever made it up.
        assert!(!catalog("axis").unwrap().is_unwritten());
        let generated = Chart::new(catalog("axis").unwrap().bars, ChartOrigin::Generated);
        assert!(!generated.is_unwritten());
        // And an empty *given* chart is something somebody cleared, not a request to invent.
        assert!(!Chart::new(Vec::new(), ChartOrigin::Given).is_unwritten());
    }

    #[test]
    fn a_catalogue_entry_can_be_named_and_repeated() {
        let once = Chart::parse("@axis").unwrap();
        let twice = Chart::parse("@axis x2").unwrap();
        assert_eq!(once.bar_count(), 4);
        assert_eq!(twice.bar_count(), 8);
        assert_eq!(twice.bars[4], once.bars[0]);
        assert!(Chart::parse("@nonsense").is_none());
    }

    #[test]
    fn the_japanese_names_reach_the_same_charts() {
        assert_eq!(catalog("丸サ進行"), catalog("marusa"));
        assert_eq!(catalog("王道進行"), catalog("royal-road"));
        assert_eq!(catalog("小悪魔"), catalog("koakuma"));
    }

    #[test]
    fn a_chart_round_trips_through_its_text() {
        let chart = Chart::parse("| IVmaj7 | III7 | vi7 | I7 |").unwrap();
        assert_eq!(chart.to_string(), "| IVmaj7 | III7 | vi7 | I7 |");
        assert_eq!(Chart::parse(&chart.to_string()).unwrap().bars, chart.bars);
    }

    #[test]
    fn nonsense_is_rejected_rather_than_silently_dropped() {
        assert!(Chart::parse("| I | nonsense |").is_none());
        assert!(Chart::parse("").is_none());
        assert!(Chart::parse("| |").is_none());
    }

    /// The chords a chart makes in `key`, read the way the composer reads it.
    fn played_in(chart: &Chart, key_text: &str) -> Vec<String> {
        let key = key(key_text);
        chart
            .spelled_in(key)
            .resolve(key, BAR)
            .iter()
            .map(|event| event.chord.to_string())
            .collect()
    }

    #[test]
    fn a_named_progression_is_the_same_loop_in_the_other_mode() {
        // 丸サ進行 is those four chords. Asked for in a minor key, reading its degrees literally
        // gave Fmaj7 – Eb7 – Abm7 – C7, which shares one chord with the loop anybody means by
        // the name and lands nowhere near it. The relative key is where a major-mode chart is
        // written when the piece is minor: the same four chords, centred where the piece is.
        assert_eq!(
            played_in(&catalog("marusa").unwrap(), "C minor"),
            ["Abmaj7", "G7", "Cm7", "Eb7"],
            "丸サ進行 centred on C minor"
        );
        // Which is E flat major's — the relative — chord for chord.
        assert_eq!(
            played_in(&catalog("marusa").unwrap(), "C minor"),
            played_in(&catalog("marusa").unwrap(), "Eb major"),
        );
        // And in A minor it is C major's, which is the famous voicing itself: the loop is the
        // one that never lands on a tonic, so either name for the key is right about it.
        assert_eq!(
            played_in(&catalog("marusa").unwrap(), "A minor"),
            ["Fmaj7", "E7", "Am7", "C7"],
        );

        // The numerals come back spelled for the key the piece is in, so the lane and the
        // chords agree about the same bar rather than one of them quietly using another key.
        let respelled: Vec<String> = catalog("marusa")
            .unwrap()
            .spelled_in(key("C minor"))
            .bars
            .iter()
            .flatten()
            .map(|numeral| numeral.to_text())
            .collect();
        assert_eq!(respelled, ["VImaj7", "V7", "i7", "III7"]);
    }

    #[test]
    fn a_minor_mode_entry_travels_the_other_way_too() {
        // The rule is not "major charts get moved": it is that a quotation keeps its chords.
        assert_eq!(
            played_in(&catalog("epic").unwrap(), "C minor"),
            ["Cm", "Ab", "Eb", "Bb"],
            "written for a minor key, so C minor reads it as it stands"
        );
        assert_eq!(
            played_in(&catalog("epic").unwrap(), "C major"),
            ["Am", "F", "C", "G"],
            "and in a major key it is the loop on the relative minor"
        );
    }

    #[test]
    fn a_chart_written_out_by_hand_is_taken_at_face_value() {
        // Nobody named it, so nothing knows what mode it is in — and the person who typed the
        // degrees meant those degrees.
        let hand = Chart::parse("| i | bVI | bIII | bVII |").unwrap();
        assert_eq!(hand.mode, None);
        assert_eq!(played_in(&hand, "C minor"), ["Cm", "Ab", "Eb", "Bb"]);
        assert_eq!(
            played_in(&hand, "C major"),
            ["Cm", "Ab", "Eb", "Bb"],
            "the same degrees, whatever the key calls itself"
        );
    }

    #[test]
    fn a_quotation_remembers_the_name_it_was_quoted_from() {
        // Which is how the mode survives being written to a file: a chart spelled out in
        // numerals cannot say which mode it was written in, and a name can.
        assert_eq!(
            Chart::parse("@marusa").unwrap().quoted_as.as_deref(),
            Some("marusa")
        );
        assert_eq!(
            Chart::parse("@丸サ進行").unwrap().quoted_as.as_deref(),
            Some("marusa"),
            "the canonical name, not the one that was asked for"
        );
        assert_eq!(
            Chart::parse("@axis x2").unwrap().quoted_as.as_deref(),
            Some("axis x2"),
            "the repeat count too, or the chart would come back half as long"
        );
        assert_eq!(Chart::parse("| I | V |").unwrap().quoted_as, None);
    }

    #[test]
    fn a_stray_pipe_is_refused_rather_than_swallowed() {
        // A doubled pipe used to be skipped by the same rule that makes the outer pipes optional,
        // so the chart came back a bar short and every chord after the gap played a bar early.
        // The prompt that reads a section's chart hands raw typed text straight to this, so the
        // typo had no other gate to meet.
        assert_eq!(Chart::parse("| I | V | IV |").unwrap().bar_count(), 3);
        assert_eq!(Chart::parse("I | V | IV").unwrap().bar_count(), 3);
        assert_eq!(Chart::parse("I").unwrap().bar_count(), 1);

        assert!(Chart::parse("| I | | V | IV |").is_none(), "doubled pipe");
        assert!(
            Chart::parse("I | | V").is_none(),
            "doubled pipe, no outer pipes"
        );
        assert!(Chart::parse("| I |  | | IV |").is_none(), "two of them");
        assert!(Chart::parse("||||").is_none());
        assert!(Chart::parse("|").is_none());
        assert!(Chart::parse("").is_none());
    }

    #[test]
    fn what_display_writes_is_what_parse_reads() {
        // The two have to agree, or a chart saved into a document is a chart that cannot be
        // opened. `Display` writes the outer pipes; `parse` is what has just learnt which ones
        // are optional and which are a mistake.
        for text in ["| I | V | IV |", "I V | vi", "| IVmaj7 | III7 | vi | I7 |"] {
            let chart = Chart::parse(text).expect("the fixture parses");
            let written = chart.to_string();
            let again = Chart::parse(&written).expect("what Display wrote, parse reads");
            assert_eq!(again.bar_count(), chart.bar_count(), "{written}");
            assert_eq!(again.to_string(), written);
        }
    }
}
